[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "test-project"
version = "0.2.0"
description = "Just testing mike."
readme = "README.md"

[project.optional-dependencies]
docs = ["mkdocs", "mkdocs-material", "mike"]
