name: Deploy Documentation

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install .[docs]
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
      - name: Deploy Documentation
        run: |
          if [ "${{ inputs.version }}" == "dev" ]; then
            mike deploy --push --update-aliases dev
          else
            mike deploy --push --update-aliases ${{ inputs.version }} latest
            mike set-default latest --push
          fi
