name: Release

on:
  release:
    types: [prereleased, released]

jobs:
  deploy-docs:
    name: Deploy Documentation
    uses: ./.github/workflows/deploy-docs.yml
    with:
      version: ${{ github.event.release.tag_name }}
    permissions:
      contents: write
